name: Generate Snake Animation

on:
  schedule: # run daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Mr-Bathwal
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
